# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
defaults: &defaults
  #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #### expecting it in the form of
  ####   /go/src/github.com/circleci/go-tool
  ####   /go/src/bitbucket.org/circleci/go-tool
  working_directory: /go/golib/assert
default_steps: &default_steps
  steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: go mod tidy
    - run: go test -v -timeout 30s github.com/golib/assert
    - run: go test -v -timeout 30s -race github.com/golib/assert
jobs:
  go1.12:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.12

    <<: *default_steps

  go1.13:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.13

    <<: *default_steps

  go1.14:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.14

    <<: *default_steps

  go1.15:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:1.15

    <<: *default_steps

  latest:
    <<: *defaults
    docker:
      # specify the version
      - image: circleci/golang:latest

    <<: *default_steps

workflows:
  version: 2
  testing:
    jobs:
      - go1.12
      - go1.13
      - go1.14
      - go1.15
      - latest